name: "Setup workspace"
description: Action that checkouts the repo (actions/checkout) and sets SHAS to be used by NX (nrwl/nx-set-shas)
runs:
  using: composite
  steps:
    - name: Checkout the target branch
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
      with:
        fetch-depth: 0
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@177b48373c6dc583ce0d9257ffb484bdd232fedf #v3.0.2
      with:
        main-branch-name: ${{ github.base_ref || github.ref_name }}
    - name: Set SHAs to env
      shell: bash
      run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"