name: "Setup workspace"

# INPUTS

runs:
  using: composite
  steps:
    - name: Checkout the target branch
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
      with:
        fetch-depth: 0
        ref: ${{ github.base_ref }}
        # token: ${{ steps.generate-token.outputs.token }}
    - name: test
      shell: bash
      run: echo "Testingfff"
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3
    - name: Shas
      shell: bash
    - run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
