name: E2E Action

inputs:
  project-name:
    description: Name to be used
    type: string
    required: false
    default: ''
  last:
    description: Last Name
    type: string
    required: false
    default: 'Alexandre'
  first:
    description: First Name
    type: string
    required: false
    default: 'HenRiquE'
outputs:
  project-name:
    description: "The project name"
    value: ${{ steps.model-bank.outputs.tag-name || steps.rnd.outputs.tag-name }}

runs:
  using: "composite"
  steps:
    - name: Print all
      shell: bash
      run: |
        echo ${{ inputs.last }} ${{ inputs.first }} ${{ inputs.project-name }}
    - name: Create project name
      id: created
      if: ${{ inputs.project-name == '' }}
      shell: bash
      run: |
        echo ${{ inputs.last }} ${{ inputs.first }} FOO
    - name: Create project name
      id: provided
      if: ${{ inputs.project-name != '' }}
      shell: bash
      run: |
        echo ${{ inputs.project-name }} FOO