name: "Testing Inputs"

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: Name to be used
        type: string
        required: false
        default: ''
      last:
        description: Last Name
        type: string
        required: false
        default: 'Alexandre'
      first:
        description: First Name
        type: string
        required: false
        default: 'HenRiquE'

jobs:
  jobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
      - name: Env
        uses: ./.github/actions/e2e
        with:
          browser:  ${{inputs.project-name || CS-${{inputs.first}}-${{inputs.last}}}}