name: "Test"

on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
  jobName:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Env
        uses: ./.github/actions/e2e
        with:
          environment: 'aaa'
          suite: 'bbb'
          browser: 'ccc'