name: "Testing Inputs"

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: Name to be used
        type: string
        required: false
        default: ''
      last:
        description: Last Name
        type: string
        required: false
        default: 'Alexandre'
      first:
        description: First Name
        type: string
        required: false
        default: 'HenRiquE'
jobs:
  nameFinal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
      - name: Scanner
        uses: ./.github/actions/e2e
        with:
          first: ${{inputs.first}}
          last: ${{inputs.last}}
          project-name: ${{inputs.project-name}}
          # browser:  CS-${{inputs.first}}-${{inputs.last}}- ${{needs.nameConstruction.outputs.browserName}}