name: "Testing Inputs"

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: Name to be used
        type: string
        required: false
        default: ''
      last:
        description: Last Name
        type: string
        required: false
        default: 'Alexandre'
      first:
        description: First Name
        type: string
        required: false
        default: 'HenRiquE'
jobs:
  nameConstruction:
    runs-on: ubuntu-latest
    outputs:
      browserName: ${{ steps.nameConstruction.outputs.test }}
    steps:
      - id: nameConstruction
        run: |
          echo "test=${${{inputs.project-name}}:+${{inputs.first}}FOO}" >> "$GITHUB_OUTPUT"

# echo ${first:+${second}FOO} 
  nameFinal:
    runs-on: ubuntu-latest
    needs: nameConstruction
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
      - name: Env
        uses: ./.github/actions/e2e
        with:
          browser:  CS-${{inputs.first}}-${{inputs.last}}- ${{needs.nameConstruction.outputs.browserName}}