name: "Build"

on:
  workflow_dispatch:
    inputs:
      appName:
        type: string
        description: Just a flag
        default: testing


jobs:
  myjob:
    runs-on: ubuntu-latest
    name: My Job
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.6.0
        with:
          node-version: 14
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3.2.0
      - name: Checkout
        uses: ./.github/actions/setup
