name: "Build"

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Just a project name
        default: ''


jobs:
  falseJobQuotes:
    runs-on: ubuntu-latest
    name: Testing Input
    steps:
      - name: Input evaluation
        shell: bash
        run: |
          echo ${{}}